### ISSUE TITLE
Reference error setting flow variables

### ISSUE THREAD

**Issue by i8beef** [Steveorevo/node-red-contrib-credentials#2]
Am I missing something in my install or usage of this node? I'm trying to set a flow variable, and I'm getting the following error.

ReferenceError: flowContext is not defined
    at setContextPropertyValue (/data/node_modules/node-red-contrib-credentials/credentials/credentials.js:24:15)
    at credentials.<anonymous> (/data/node_modules/node-red-contrib-credentials/credentials/credentials.js:41:11)
    at emitOne (events.js:96:13)
    at credentials.emit (events.js:188:7)
    at credentials.Node.receive (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/Node.js:215:14)
    at InjectNode.Node.send (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at InjectNode.<anonymous> (/usr/src/node-red/node_modules/node-red/nodes/core/core/20-inject.js:77:22)
    at emitOne (events.js:96:13)
    at InjectNode.emit (events.js:188:7)
    at InjectNode.Node.receive (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/Node.js:215:14)

**Comment by Steveorevo** [comment]
Looks like you've found a legitimate bug. Will update here in 1 minute.

**Comment by Steveorevo** [comment]
Fixed in commit. Created a new version 0.2.0; wait a few minutes for the repo to update and try uninstall/re-install. e01ccb87beeadd4b7c23f4b00b8eb6845dfb6021

**Comment by Steveorevo** [comment]
Refresh requested, when the version bumps to 0.2.0 here, it should be available to install in Node-RED via the manage palette pull down menu. 
https://flows.nodered.org/node/node-red-contrib-credentials

**Comment by i8beef** [comment]
Nice turn around, thank you sir!
